language: c

compiler:
    - clang
    - gcc

before_install:
    - uname -a
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install valgrind libyaml-dev libpcap0.8-dev libpcap0.8 libprotobuf-c0 libprotobuf-c0-dev protobuf-c-compiler python-yaml

install: true

before_script: true

script:
    - make dep
    - make -j4 && make clean
    - make debug=true -j4 && make clean

after_script: true

after_success: true

after_failure: true

notifications:
    email:
      - hyzwowtools@gmail.com
