#language: c

env:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

before_install:
    - uname -a
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install valgrind libyaml-dev libprotobuf-dev protobuf-compiler libprotobuf-c0 libprotobuf-c0-dev protobuf-c-compiler python-yaml expect libc-ares-dev
    - gcc --version
    - g++ --version
    - clang --version
    - clang++ --version

install: true

before_script: true

script:
    - make -j4 dep
    - sudo make install-dep
    - make debug=true -j4
    - make clean
    - make -j4 disable_jemalloc=true
    - sudo make install
    - make check debug=true

after_success: true

after_script: true

after_failure: false

notifications:
    email:
      - hyzwowtools@gmail.com
