#language: c

env:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

before_install:
    - uname -a
    - gcc --version
    - g++ --version
    - clang --version
    - clang++ --version
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install valgrind libyaml-dev libprotobuf-dev libprotobuf-c0 libprotobuf-c0-dev protobuf-c-compiler python-yaml

install: true

before_script: true

script:
    - make -j4 dep
    - make -j4
    - make clean
    - make debug=true -j4

after_success: sudo make install

after_script: true

after_failure: true

notifications:
    email:
      - hyzwowtools@gmail.com
