thread_num: 1
command_port: 7759
bio: 1
log_name: skull.log
log_level: debug

workflows:

# If you want to set the max_queue_size, use 'max_qsize' for the service item
services:

languages: [cpp]

# max open files (This requires to start the engine with root permission)
## max_fds: 65535
