thread_num: 1
command_port: 7759
bio: 1
log_name: skull.log
log_level: debug

workflows:

services:

languages: [cpp]

# max open files (This requires to start the engine with root permission)
## max_fds: 65535
