# how many threads the skull engine will create
thread_num: 1

# working flow
workflows:
    - modules: [test, abc, test]
      concurrent: 1
      port: 7758
    - modules: [t4, t3, t2]
      concurrent: 0

